### ISSUE TITLE
Reactome not properly updated

### ISSUE THREAD

**Issue by tropicalberto** [C3c6e6/GeneSets#2]
I am using your package for building the gene set file for Reactome (Homo sapiens). I have run the script today, but nonetheless the generated output does not match with the last release of Reactome (_v64_, https://reactome.org/download/current/ReactomePathways.gmt.zip). In this case, the output from **GeneSets** contains 1860 gene sets, whereas that the last release of Reactome has 2022 gene sets. I checked the overlap between the gene sets of **GeneSets** output and Reactome v64, and the intersection has 1836 gene sets. That may me think that perhaps the retrieval of Reactome gene sets is not done in a way that it is completely up to date (I could also not guess which version of Reactome matches with the **GeneSets** output). Do you have any tips about how to fix this issue? 

Thanks a lot in advance

**Comment by C3c6e6** [comment]
Hi!

Apologies for the absurdly late reply. The problem is  however upstream with the NCBI Biosystems database (https://www.ncbi.nlm.nih.gov/biosystems/). The GeneSets package extracts most of its gene set definitions from this resource. It is possible that the people over at NCBI are a bit slow in incorporating the latest release of Reactome.
